import { useState } from "react";
import type { FlowDocSpec, RouteDoc } from "../types/spec.js";
import { MethodBadge } from "./MethodBadge.js";

interface SidebarProps {
  spec: FlowDocSpec;
  selectedRoute: RouteDoc | null;
  onSelect: (route: RouteDoc) => void;
}

export const Sidebar = ({ spec, selectedRoute, onSelect }: SidebarProps): JSX.Element => {
  const [search, setSearch] = useState("");
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());

  const query = search.toLowerCase();

  const toggleGroup = (name: string): void => {
    setCollapsed((prev) => {
      const next = new Set(prev);
      next.has(name) ? next.delete(name) : next.add(name);
      return next;
    });
  };

  const filteredGroups = spec.groups
    .map((group) => ({
      ...group,
      routes: group.routes.filter(
        (r) =>
          !query ||
          r.path.toLowerCase().includes(query) ||
          r.method.toLowerCase().includes(query) ||
          (r.summary?.toLowerCase().includes(query) ?? false)
      ),
    }))
    .filter((g) => g.routes.length > 0);

  return (
    <aside className="w-64 shrink-0 flex flex-col border-r border-slate-800 h-screen sticky top-0 overflow-hidden">
      {/* Logo / title */}
      <div className="px-4 py-5 border-b border-slate-800">
        <div className="flex items-center gap-2">
          <span className="text-[var(--brand)] font-bold text-lg tracking-tight">
            {spec.info.title}
          </span>
          <span className="text-xs text-slate-600 font-mono">v{spec.info.version}</span>
        </div>
        {spec.info.description && (
          <p className="text-xs text-slate-500 mt-1 leading-relaxed">{spec.info.description}</p>
        )}
      </div>

      {/* Search */}
      <div className="px-3 py-3 border-b border-slate-800">
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search routes…"
          className="w-full bg-slate-900 border border-slate-700 rounded-md px-3 py-1.5 text-xs text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-[var(--brand)] transition-colors"
        />
      </div>

      {/* Route list */}
      <nav className="flex-1 overflow-y-auto py-2">
        {filteredGroups.map((group) => {
          const isCollapsed = collapsed.has(group.name);
          return (
            <div key={group.name} className="mb-1">
              <button
                onClick={() => toggleGroup(group.name)}
                className="w-full flex items-center justify-between px-4 py-2 text-[11px] font-semibold uppercase tracking-widest text-slate-500 hover:text-slate-300 transition-colors"
              >
                <span>{group.name}</span>
                <span className="text-[10px]">{isCollapsed ? "▸" : "▾"}</span>
              </button>

              {!isCollapsed && (
                <ul className="flex flex-col gap-0.5 px-2">
                  {group.routes.map((route) => {
                    const isSelected =
                      selectedRoute?.method === route.method &&
                      selectedRoute?.path === route.path;

                    return (
                      <li key={`${route.method}:${route.path}`}>
                        <button
                          onClick={() => onSelect(route)}
                          className={`w-full flex items-center gap-2 px-2 py-1.5 rounded-md text-left transition-colors ${
                            isSelected
                              ? "bg-slate-800 text-slate-100"
                              : "text-slate-400 hover:text-slate-200 hover:bg-slate-800/50"
                          }`}
                        >
                          <MethodBadge method={route.method} size="sm" />
                          <span className="font-mono text-[11px] truncate">{route.path}</span>
                        </button>
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>
          );
        })}
      </nav>

      {/* Footer */}
      <div className="px-4 py-3 border-t border-slate-800">
        <p className="text-[10px] text-slate-600">
          Generated by{" "}
          <span className="text-[var(--brand)] font-semibold">flowdoc</span>
        </p>
      </div>
    </aside>
  );
};
