import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import chalk from "chalk";

const CONFIG_TEMPLATE = `import { defineConfig } from "flowdoc-gen";

export default defineConfig({
  name: "My API",
  version: "1.0.0",
  description: "API documentation generated by flowdoc",
  framework: "express",
  entry: "./src",
  output: "./docs-output",
  theme: {
    brand: "#6366f1",
    darkMode: true,
  },
  // groups: [
  //   { name: "Auth",  match: "/auth/**" },
  //   { name: "Users", match: "/users/**" },
  // ],
});
`;

export const init = (cwd: string = process.cwd()): void => {
  const configPath = resolve(cwd, "flowdoc.config.ts");

  if (existsSync(configPath)) {
    console.log(chalk.yellow("  flowdoc.config.ts already exists — skipping."));
    return;
  }

  writeFileSync(configPath, CONFIG_TEMPLATE, "utf-8");

  console.log();
  console.log(`  ${chalk.bold("flowdoc")} initialized`);
  console.log();
  console.log(`  Created ${chalk.cyan("flowdoc.config.ts")}`);
  console.log();
  console.log("  Next steps:");
  console.log(`    1. Edit ${chalk.cyan("flowdoc.config.ts")} — set your entry path`);
  console.log(`    2. Run ${chalk.cyan("flowdoc generate")} to build your docs`);
  console.log(`    3. Run ${chalk.cyan("flowdoc serve")} to preview locally`);
  console.log();
};
