import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import chalk from "chalk";

const CONFIG_TEMPLATE = `import type { FlowDocConfig } from "@flowdoc/core";

const config: FlowDocConfig = {
  name: "My API",
  version: "1.0.0",
  description: "API documentation generated by flowdoc",
  framework: "express",
  entry: "./src",           // folder or file containing your Express routes
  baseUrl: "http://localhost:3000",
  auth: {
    type: "bearer",
  },
  output: "./docs-output",
  theme: {
    brand: "#6366f1",
    darkMode: true,
  },
  // Optional: manually group routes under named sections
  // groups: {
  //   "User Management": ["/users/**"],
  //   "Auth": ["/auth/**"],
  // },
};

export default config;
`;

export const init = (cwd: string = process.cwd()): void => {
  const configPath = resolve(cwd, "flowdoc.config.ts");

  if (existsSync(configPath)) {
    console.log(chalk.yellow("  flowdoc.config.ts already exists — skipping."));
    return;
  }

  writeFileSync(configPath, CONFIG_TEMPLATE, "utf-8");

  console.log();
  console.log(`  ${chalk.bold("flowdoc")} initialized`);
  console.log();
  console.log(`  Created ${chalk.cyan("flowdoc.config.ts")}`);
  console.log();
  console.log("  Next steps:");
  console.log(`    1. Edit ${chalk.cyan("flowdoc.config.ts")} — set your entry path`);
  console.log(`    2. Run ${chalk.cyan("flowdoc generate")} to build your docs`);
  console.log(`    3. Run ${chalk.cyan("flowdoc serve")} to preview locally`);
  console.log();
};
