import { writeFileSync, existsSync, readFileSync } from "fs";
import { resolve } from "path";
import chalk from "chalk";

type Framework = "express" | "nestjs" | "fastify" | "hono" | "koa";

const detectFramework = (cwd: string): Framework => {
  const pkgPath = resolve(cwd, "package.json");
  if (!existsSync(pkgPath)) return "express";
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    if ("@nestjs/core" in allDeps || "@nestjs/common" in allDeps) return "nestjs";
    if ("fastify" in allDeps) return "fastify";
    if ("hono" in allDeps) return "hono";
    if ("koa" in allDeps) return "koa";
  } catch {
    // malformed package.json — fall back to express
  }
  return "express";
};

const buildConfigTemplate = (framework: Framework): string =>
  `import { defineConfig } from "flowdoc-gen";

export default defineConfig({
  name: "My API",
  version: "1.0.0",
  description: "API documentation generated by flowdoc",
  framework: "${framework}",
  entry: "./src",
  output: "./docs-output",
  theme: {
    brand: "#6366f1",
    darkMode: true,
  },
  // groups: [
  //   { name: "Auth",  match: "/auth/**" },
  //   { name: "Users", match: "/users/**" },
  // ],
});
`;

export const init = (cwd: string = process.cwd()): void => {
  const configPath = resolve(cwd, "flowdoc.config.ts");

  if (existsSync(configPath)) {
    console.log(chalk.yellow("  flowdoc.config.ts already exists — skipping."));
    return;
  }

  const framework = detectFramework(cwd);
  writeFileSync(configPath, buildConfigTemplate(framework), "utf-8");

  console.log();
  console.log(`  ${chalk.bold("flowdoc")} initialized`);
  console.log();
  console.log(`  Created ${chalk.cyan("flowdoc.config.ts")}`);
  console.log(`  Detected framework: ${chalk.green(framework)}`);
  console.log();
  console.log("  Next steps:");
  console.log(`    1. Edit ${chalk.cyan("flowdoc.config.ts")} — set your entry path`);
  console.log(`    2. Run ${chalk.cyan("flowdoc generate")} to build your docs`);
  console.log(`    3. Run ${chalk.cyan("flowdoc serve")} to preview locally`);
  console.log();
};
